{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPVIi0N2WFjECSqN37XY80/",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/marina554/excel_automation/blob/main/aggregate_sales(Excel%E8%87%AA%E5%8B%95%E9%9B%86%E8%A8%88%E3%83%84%E3%83%BC%E3%83%AB).py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "RtCRGO341Cjm"
      },
      "outputs": [],
      "source": [
        "import pandas as pd\n",
        "import glob\n",
        "import os\n",
        "from datetime import datetime\n",
        "\n",
        "# ========= 設定 ========= #\n",
        "DATA_DIR = \"data\"\n",
        "OUTPUT_DIR = \"output\"\n",
        "OUTPUT_FILE = f\"{OUTPUT_DIR}/aggregated_sales_{datetime.now().strftime('%Y%m%d')}.xlsx\"\n",
        "DATE_COL = \"date\"\n",
        "STORE_COL = \"store\"\n",
        "SALES_COL = \"sales\"\n",
        "\n",
        "# ========================= #\n",
        "\n",
        "def read_files(data_dir):\n",
        "    \"\"\"フォルダ内の Excel / CSV を読み込む\"\"\"\n",
        "    file_list = glob.glob(os.path.join(data_dir, \"*\"))\n",
        "    dfs = []\n",
        "\n",
        "    for file in file_list:\n",
        "        if file.endswith((\".xlsx\", \".xls\")):\n",
        "            df = pd.read_excel(file)\n",
        "        elif file.endswith(\".csv\"):\n",
        "            df = pd.read_csv(file)\n",
        "        else:\n",
        "            continue\n",
        "\n",
        "        dfs.append(df)\n",
        "\n",
        "    return pd.concat(dfs, ignore_index=True)\n",
        "\n",
        "\n",
        "def clean_data(df):\n",
        "    \"\"\"欠損補完、型変換、列名統一などのクリーニング\"\"\"\n",
        "    # 列名を小文字化\n",
        "    df.columns = [c.lower() for c in df.columns]\n",
        "\n",
        "    # 必須列がなければエラー\n",
        "    required_cols = [DATE_COL, STORE_COL, SALES_COL]\n",
        "    for col in required_cols:\n",
        "        if col not in df.columns:\n",
        "            raise ValueError(f\"必要な列が見つかりません: {col}\")\n",
        "\n",
        "    # 日付を変換\n",
        "    df[DATE_COL] = pd.to_datetime(df[DATE_COL], errors=\"coerce\")\n",
        "\n",
        "    # 欠損値処理\n",
        "    df[STORE_COL] = df[STORE_COL].fillna(\"Unknown\")\n",
        "    df[SALES_COL] = pd.to_numeric(df[SALES_COL], errors=\"coerce\").fillna(0)\n",
        "\n",
        "    return df\n",
        "\n",
        "\n",
        "def aggregate(df):\n",
        "    \"\"\"日付 × 店舗 の売上集計\"\"\"\n",
        "    df_summary = (\n",
        "        df.groupby([STORE_COL, DATE_COL])[SALES_COL]\n",
        "        .sum()\n",
        "        .reset_index()\n",
        "        .sort_values([STORE_COL, DATE_COL])\n",
        "    )\n",
        "    return df_summary\n",
        "\n",
        "\n",
        "def save_to_excel(df, output_path):\n",
        "    \"\"\"Excel形式で保存\"\"\"\n",
        "    os.makedirs(os.path.dirname(output_path), exist_ok=True)\n",
        "\n",
        "    with pd.ExcelWriter(output_path, engine=\"openpyxl\") as writer:\n",
        "        df.to_excel(writer, index=False, sheet_name=\"summary\")\n",
        "\n",
        "    print(f\"出力完了: {output_path}\")\n",
        "\n",
        "\n",
        "def main():\n",
        "    print(\"=== 売上データ集計ツール ===\")\n",
        "\n",
        "    df = read_files(DATA_DIR)\n",
        "    df = clean_data(df)\n",
        "\n",
        "    df_summary = aggregate(df)\n",
        "\n",
        "    save_to_excel(df_summary, OUTPUT_FILE)\n",
        "\n",
        "    print(\"処理が完了しました！\")\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()\n"
      ]
    }
  ]
}